package visualization;

public enum FieldType {
    ANIMAL_LOWEST_ENERGY,
    ANIMAL_LOW_ENERGY,
    ANIMAL_MID_ENERGY,
    ANIMAL_HIGH_ENERGY,
    ANIMAL_ENERGY_OVER_9000,
    ANIMAL_TRACKED,
    PLANT,
    JUNGLE,
    STEPPE
}
